# =====================================================================
# EXERCISE 8.1: REGISTER ENDPOINT
# =====================================================================
# Goal: Create a user registration API endpoint that:
#   - Accepts username, email, and password via JSON POST request
#   - Validates all required fields
#   - Hashes the password before storing (NEVER store plain text passwords!)
#   - Stores the user in a SQLite database using SQLAlchemy
#   - Returns appropriate success/error responses
#
# Key Concepts:
#   - Password hashing with werkzeug.security
#   - Input validation for API endpoints
#   - Proper HTTP status codes (201 Created, 400 Bad Request, 409 Conflict)
# =====================================================================

from flask import Flask, jsonify, request
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import declarative_base, sessionmaker
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.exceptions import BadRequest

app = Flask(__name__)

# --- Database Setup ---
engine = create_engine('sqlite:///exercise_8_1.db', echo=False)
Base = declarative_base()


# --- User Model ---
class User(Base):
    """
    User model for storing user credentials.
    
    IMPORTANT: We NEVER store plain-text passwords!
    Instead, we store a hash generated by werkzeug.security.generate_password_hash().
    This uses PBKDF2 (Password-Based Key Derivation Function 2) by default,
    which is a one-way function — you can verify a password against a hash,
    but you cannot reverse the hash back to the original password.
    """
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    username = Column(String(50), nullable=False, unique=True)
    email = Column(String(100), nullable=False, unique=True)
    password_hash = Column(String(256), nullable=False)  # Store HASH, not password

    def set_password(self, password):
        """
        Hashes the password and stores it.
        generate_password_hash() creates a salted hash, meaning even
        two identical passwords will produce different hashes.
        """
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        """
        Verifies a plain-text password against the stored hash.
        Returns True if it matches, False otherwise.
        """
        return check_password_hash(self.password_hash, password)

    def to_dict(self):
        """Returns a safe dictionary representation (no password hash!)."""
        return {
            "id": self.id,
            "username": self.username,
            "email": self.email
        }

    def __repr__(self):
        return f"<User('{self.username}', '{self.email}')>"


# Create the tables
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)


# --- Error Handlers ---

@app.errorhandler(400)
def bad_request(error):
    message = error.description if hasattr(error, 'description') else "Bad request"
    return jsonify({"error": "Bad Request", "message": message}), 400

@app.errorhandler(409)
def conflict(error):
    message = error.description if hasattr(error, 'description') else "Conflict"
    return jsonify({"error": "Conflict", "message": message}), 409

@app.errorhandler(500)
def internal_error(error):
    return jsonify({"error": "Internal Server Error", "message": "An unexpected error occurred."}), 500


# --- Register Endpoint ---

@app.route('/register', methods=['POST'])
def register():
    """
    POST /register
    
    Registers a new user account.
    
    Request Body (JSON):
        {
            "username": "john_doe",
            "email": "john@example.com",
            "password": "securepassword123"
        }
    
    Success Response (201 Created):
        {
            "message": "User registered successfully",
            "user": { "id": 1, "username": "john_doe", "email": "john@example.com" }
        }
    
    Error Responses:
        400 - Missing or invalid fields
        409 - Username or email already exists
    """
    # 1. Parse JSON body
    data = request.get_json(silent=True)
    if data is None:
        raise BadRequest("Invalid JSON format or missing Request Body.")

    # 2. Validate required fields
    required_fields = ['username', 'email', 'password']
    for field in required_fields:
        if field not in data:
            raise BadRequest(f"Field '{field}' is required.")

    username = data['username']
    email = data['email']
    password = data['password']

    # 3. Validate field types and content
    if not isinstance(username, str) or not username.strip():
        raise BadRequest("Field 'username' must be a non-empty string.")
    if not isinstance(email, str) or not email.strip():
        raise BadRequest("Field 'email' must be a non-empty string.")
    if not isinstance(password, str) or len(password) < 6:
        raise BadRequest("Field 'password' must be a string with at least 6 characters.")

    # Simple email format check
    if '@' not in email or '.' not in email:
        raise BadRequest("Field 'email' must be a valid email address.")

    username = username.strip()
    email = email.strip().lower()

    # 4. Check for existing users (uniqueness)
    session = Session()
    try:
        if session.query(User).filter_by(username=username).first():
            return jsonify({"error": "Conflict", "message": "Username already exists."}), 409
        if session.query(User).filter_by(email=email).first():
            return jsonify({"error": "Conflict", "message": "Email already registered."}), 409

        # 5. Create the user with a HASHED password
        new_user = User(username=username, email=email)
        new_user.set_password(password)  # Hash it!

        session.add(new_user)
        session.commit()

        return jsonify({
            "message": "User registered successfully",
            "user": new_user.to_dict()
        }), 201

    except Exception as e:
        session.rollback()
        return jsonify({"error": "Internal Server Error", "message": str(e)}), 500
    finally:
        session.close()


# --- Helper Route: List all users (for testing/debugging) ---

@app.route('/users', methods=['GET'])
def list_users():
    """GET /users - Returns all registered users (without password hashes)."""
    session = Session()
    try:
        users = session.query(User).all()
        return jsonify([u.to_dict() for u in users]), 200
    finally:
        session.close()


if __name__ == '__main__':
    print("\n=== Exercise 8.1: Register Endpoint ===")
    print("Test with curl or Postman:")
    print('  POST http://localhost:5000/register')
    print('  Body: {"username": "john", "email": "john@example.com", "password": "secret123"}')
    print("  GET  http://localhost:5000/users  (list all users)\n")
    app.run(debug=True, port=5000)
