from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import declarative_base, sessionmaker

# 1. SETUP DATABASE ENGINE
# We use SQLite for simplicity. 'sqlite:///exercise_7_1.db' creates a local file database.
# echo=True allows us to see the actual SQL queries generated by SQLAlchemy.
engine = create_engine('sqlite:///exercise_7_1.db', echo=True)

# 2. CREATE A BASE CLASS
# All our models will inherit from this Base class.
# It maintains a catalog of classes and tables relative to that base.
Base = declarative_base()

# 3. DEFINE THE MODEL
class User(Base):
    """
    User model representing a 'users' table in the database.
    """
    __tablename__ = 'users' # The actual table name in the database

    # Define columns
    id = Column(Integer, primary_key=True) # Primary key automatically auto-increments
    username = Column(String(50), nullable=False, unique=True) # Cannot be null, must be unique
    email = Column(String(100), nullable=False, unique=True)

    def __repr__(self):
        # This helps in printing the object in a readable format
        return f"<User(username='{self.username}', email='{self.email}')>"

# 4. CREATE TABLES
# This tells the engine to look at all classes inheriting from Base and create tables for them.
Base.metadata.create_all(engine)

# 5. SETUP SESSION
# A session is the "workspace" for your objects. It handles the transactions.
Session = sessionmaker(bind=engine)
session = Session()

def run_crud_operations():
    """
    Demonstrates Create, Read, Update, and Delete operations using SQLAlchemy.
    """
    print("\n--- STARTING CRUD OPERATIONS ---\n")

    # ==========================================
    # C - CREATE
    # ==========================================
    print("1. CREATE")
    # Create new User objects
    new_user1 = User(username='john_doe', email='john@example.com')
    new_user2 = User(username='jane_smith', email='jane@example.com')

    # Add them to the session
    session.add(new_user1)
    session.add(new_user2)
    
    # Commit the transaction to save them to the database
    session.commit()
    print(f"Created users: {new_user1.username}, {new_user2.username}")

    # ==========================================
    # R - READ
    # ==========================================
    print("\n2. READ")
    # Read all users
    all_users = session.query(User).all()
    print("All users in DB:", all_users)

    # Read a specific user by filtering
    john = session.query(User).filter_by(username='john_doe').first()
    print("Found user:", john)

    # ==========================================
    # U - UPDATE
    # ==========================================
    print("\n3. UPDATE")
    # Update the user's email
    if john:
        john.email = 'john.doe_new@example.com'
        # Commit saves the changes. We don't need to session.add(john) again
        # because the session is already tracking this object.
        session.commit()
        print(f"Updated John's email to: {john.email}")

    # ==========================================
    # D - DELETE
    # ==========================================
    print("\n4. DELETE")
    # Let's delete jane_smith
    jane = session.query(User).filter_by(username='jane_smith').first()
    if jane:
        session.delete(jane)
        session.commit()
        print(f"Deleted user: {jane.username}")

    # Verify deletion
    remaining_users = session.query(User).all()
    print("Remaining users:", remaining_users)
    print("\n--- END OF CRUD OPERATIONS ---")

if __name__ == '__main__':
    # To keep the example clean when run multiple times, 
    # we first clean up the users table (not recommended in production).
    session.query(User).delete()
    session.commit()
    
    run_crud_operations()
